services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun-drop-shielded
    restart: unless-stopped
    env_file:
    - .env
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - HOSTNAME=gluetun-drop-shielded
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_HOSTNAMES=${AIRVPN_SERVER}
      - FIREWALL_VPN_INPUT_PORTS=${DROP_AIRVPN_PORT},${ROMM_AIRVPN_PORT}
      - VPN_PORT_FORWARDING="${VPN_PORT_FORWARDING}"
      - BLOCK_MALICIOUS="${BLOCK_MALICIOUS}"
      - BLOCK_SURVEILLANCE="${BLOCK_SURVEILLANCE}"
      - BLOCK_ADS="${BLOCK_ADS}"
      - DOT_PROVIDERS="${DOT_PROVIDERS}"
  postgres:
    image: postgres:14-alpine
    container_name: postgres-drop-shielded
    network_mode: "service:gluetun"
    restart: unless-stopped
    env_file:
    - .env
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
    security_opt:
      - "label=disable"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - HOSTNAME=postgres-drop-shielded
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  drop:
    image: ghcr.io/drop-oss/drop:latest
    container_name: drop-drop-shielded
    network_mode: "service:gluetun"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
    - .env
    security_opt:
      - "label=disable"
    #ports:
    #  - ${DROP_AIRVPN_PORT}:3000
    volumes:
      - ${LIBRARY_PATH}:/library/
      #For Multi Library
      #- ${LIBRARY_PATH_1}:/library/1
      #- ${LIBRARY_PATH_2}:/library/2
      - ${DROP_DATA_PATH}:/data
    environment:
      - HOSTNAME=drop-drop-shielded
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-drop-shielded:5432/${POSTGRES_DB}
      - EXTERNAL_URL=http://${DROP_DDNS}:${DROP_AIRVPN_PORT}