services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun-shielded
    restart: unless-stopped
    networks:
      gluetun-shielded-network:
        ipv4_address: 172.20.0.20
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "${DROP_AIRVPN_PORT}:${DROP_AIRVPN_PORT}"
    volumes:
      - ./gluetun:/gluetun
    environment:
      - HOSTNAME=gluetun-shielded
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - FIREWALL_VPN_INPUT_PORTS=${DROP_AIRVPN_PORT}
  postgres:
    image: postgres:14-alpine
    container_name: postgres-shielded
    network_mode: "service:gluetun"
    restart: unless-stopped
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB_DROP} -U ${POSTGRES_USER_DROP}
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
    security_opt:
      - "label=disable"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - HOSTNAME=postgres-shielded
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DROP}
      - POSTGRES_USER=${POSTGRES_USER_DROP}
      - POSTGRES_DB=${POSTGRES_DB_DROP}
  nginx:
    image: nginx:alpine
    container_name: nginx-shielded
    network_mode: "service:gluetun"
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    security_opt:
      - "label=disable"
    depends_on:
      - drop
  drop:
    image: ghcr.io/drop-oss/drop:latest
    container_name: drop-shielded
    network_mode: "service:gluetun"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    security_opt:
      - "label=disable"
    volumes:
      - ${LIBRARY_PATH}:/library/
      #For Multi Library
      #- ${LIBRARY_PATH_1}:/library/1
      #- ${LIBRARY_PATH_2}:/library/2
      - ${DROP_DATA_PATH}:/data
    environment:
      - HOSTNAME=drop-shielded
      - IGDB_CLIENT_ID=${METADATA_IGDB_CLIENT_ID}
      - IGDB_CLIENT_SECRET=${METADATA_IGDB_CLIENT_SECRET}
      - DATABASE_URL=postgres://${POSTGRES_USER_DROP}:${POSTGRES_PASSWORD_DROP}@postgres-shielded:5432/${POSTGRES_DB_DROP}
      - EXTERNAL_URL=http://${DROP_DDNS}:${DROP_AIRVPN_PORT}
  gamevault-backend:
    image: phalcode/gamevault-backend:latest
    container_name: gamevault-backend-shielded
    network_mode: "service:gluetun"
    restart: unless-stopped
    environment:
      - DB_SYSTEM=SQLITE
      - container_name=gamevault-backend-shielded
      - METADATA_IGDB_CLIENT_ID=${METADATA_IGDB_CLIENT_ID}
      - METADATA_IGDB_CLIENT_SECRET=${METADATA_IGDB_CLIENT_SECRET}
    security_opt:
      - "label=disable"
    volumes:
      - ./gamevault/config:/config
      - ./gamevault/media:/media
      - ./gamevault/savefiles:/savefiles
      - ./gamevault/logs:/logs
      - ./gamevault/db:/db
      - ./gamevault/plugins:/plugins
      # Mount the folder where your games are
      - ${LIBRARY_PATH}:/files
    #ports:
    #  - 8080:8080/tcp
networks:
  gluetun-shielded-network:
    driver: bridge
    name: gluetun-shielded-network
    ipam:
      config:
        - subnet: 172.20.0.0/16