services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun-drop-shielded
    restart: unless-stopped
    env_file:
    - .env
    cap_add:
      - NET_ADMIN
      - NET_RAW
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - "${DROP_AIRVPN_PORT}:${DROP_AIRVPN_PORT}"
    volumes:
      - ./gluetun:/gluetun
    environment:
      - HOSTNAME=gluetun-drop-shielded
      - VPN_SERVICE_PROVIDER=airvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_PRESHARED_KEY=${WIREGUARD_PRESHARED_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - FIREWALL_VPN_INPUT_PORTS=${DROP_AIRVPN_PORT}
  postgres:
    image: postgres:14-alpine
    container_name: postgres-drop-shielded
    network_mode: "service:gluetun"
    restart: unless-stopped
    env_file:
    - .env
    healthcheck:
      test: pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 10s
    security_opt:
      - "label=disable"
    volumes:
      - ./db:/var/lib/postgresql/data
    environment:
      - HOSTNAME=postgres-drop-shielded
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
  traefik:
    image: traefik:v3.0
    container_name: traefik-drop-shielded
    network_mode: "service:gluetun"
    restart: unless-stopped
    env_file:
    - .env
    command:
      - --api.dashboard=true
      - --api.insecure=true
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      - --entrypoints.web.address=:${DROP_AIRVPN_PORT}
      - --log.level=INFO
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    security_opt:
      - "label=disable"
  drop:
    image: ghcr.io/drop-oss/drop:latest
    container_name: drop-drop-shielded
    network_mode: "service:gluetun"
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
    - .env
    security_opt:
      - "label=disable"
    volumes:
      - ${LIBRARY_PATH}:/library/
      #For Multi Library
      #- ${LIBRARY_PATH_1}:/library/1
      #- ${LIBRARY_PATH_2}:/library/2
      - ${DROP_DATA_PATH}:/data
    environment:
      - HOSTNAME=drop-drop-shielded
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-drop-shielded:5432/${POSTGRES_DB}
      - EXTERNAL_URL=http://${DROP_DDNS}:${DROP_AIRVPN_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.drop.rule=Host(`${DROP_DDNS}`)"
      - "traefik.http.routers.drop.entrypoints=web"
      - "traefik.http.services.drop.loadbalancer.server.port=3000"